development:
  log_level: debug
  echo_sql: false
security:
  max_content_length: 25000
  api_key_header: X-API-Key
  auth_cookie_key: auth-session
  session_timeout:
    days: 1
  password_reset_grace:
    hours: 1
  cors_policy:
    allow_all_origins: false
    allow_all_headers: false
    allow_all_methods: false
env:
  site_domain: localhost
  api_route_prefix: /api
database:
  database: project_dev
  user: project_dev_user
  password: notprodsafe
