development:
  log_level: debug
  echo_sql: false
security:
  cors_policy:
    allow_all_origins: false
    allow_all_headers: false
    allow_all_methods: false
env:
  api_route_prefix: /api
database:
  database: project_dev
  user: project_dev_user
  password: notprodsafe
